# Numeric Python

In [1]:
import numpy as np

In [16]:
# np.array
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

c = a + b
print(c)

[1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
arr_a = np.array(a)
arr_b = np.array(b)

In [18]:
type(arr_a)

numpy.ndarray

In [19]:
arr_c = arr_a * arr_b
arr_c

array([ 5, 12, 21, 32])

In [20]:
multi_d_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
multi_d_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
print(a)
print(arr_a)

[1, 2, 3, 4]
[1 2 3 4]


In [25]:
# To check shape of an array
multi_d_array.shape

(3, 4)

In [26]:
# to check size of an array
multi_d_array.size

12

In [29]:
# To check dimension of an array
multi_d_array.ndim

2

In [30]:
arr_a.ndim

1

In [36]:
# <U -> Unicode highest number of characters in a word

In [34]:
data = np.array(['Mobile', 'TV', 'Watch', 'Laptop', 'Desktop'])
data

array(['Mobile', 'TV', 'Watch', 'Laptop', 'Desktop'], dtype='<U7')

In [35]:
countries = np.array(['Bangladesh', 'Nepal', 'India', 'USA', 'UK', 'Canada'])
countries

array(['Bangladesh', 'Nepal', 'India', 'USA', 'UK', 'Canada'],
      dtype='<U10')

## Zeros and Ones

In [39]:
# zeros / ones (shape, dtype = default(float)/int)
zeros_1d = np.zeros(5, dtype=int)
zeros_1d

array([0, 0, 0, 0, 0])

In [41]:
zeros_2d = np.zeros((5, 6), dtype=int)
zeros_2d

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [42]:
ones_1d = np.ones(5, dtype=int)
ones_1d

array([1, 1, 1, 1, 1])

In [43]:
ones_2d = np.ones((5, 6), dtype=int)
ones_2d

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## Arange

In [51]:
num = []
for i in range(1, 61):
    num.append(i)
num = np.array(num)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [49]:
# Arange - Generate numbers and insert numbers into an numpy array
numbers = np.arange(1, 61)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

## Reshape and Ravel

In [ ]:
'''
- Reshape -> Change dimension of an array.
- Ravel / Flatten -> Change any dimension of array into one dimension
'''

In [52]:
numbers.shape

(60,)

In [55]:
reshape_numbers = numbers.reshape(5, 12)
reshape_numbers

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [56]:
ravel_numbers = np.ravel(reshape_numbers)
ravel_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

## Slicing

In [63]:
numbers[2:10]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
# array[row, column]
reshape_numbers[0:2, 1:3]

array([[ 2,  3],
       [14, 15]])

In [71]:
for row in reshape_numbers[0:2]:
    print(row[1:3])

[2 3]
[14 15]


In [78]:
# Slicing to extract entire column.
reshape_numbers[:,1] 

array([ 2, 14, 26, 38, 50])

## Array Broadcasting

In [ ]:
'''
Rules of Array Broadcasting
------------------
1. All shape and size of array must be equal.
2. Atleast one shape of an array must be one other must be equal.
'''

In [100]:
a_data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b_data = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

In [101]:
a_data + b_data

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Boolean Indexing

In [ ]:
'''
- Used for data filtering.

syntax
-------
array_name[condition]
'''

In [106]:
filter_numbers = numbers > 45
# array[condition] -> data filter
numbers[filter_numbers]

array([46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [107]:
numbers[numbers > 45]

array([46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [109]:
data = np.array(['Mobile', 'TV', 'Watch', 'Laptop', 'Desktop', 'Laptop', 'Desktop', 'Laptop', 'Desktop'])

In [110]:
data[data == 'Desktop']

array(['Desktop', 'Desktop', 'Desktop'], dtype='<U7')

In [111]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [121]:
sum_data = numbers.sum()
sum_data

np.int64(1830)

In [113]:
numbers.max()

np.int64(60)

In [114]:
numbers.min()

np.int64(1)

In [115]:
numbers.mean()

np.float64(30.5)

In [120]:
np.median(numbers)

np.float64(30.5)

In [122]:
np.sqrt(sum_data)

np.float64(42.77849927241488)